CREATE TABLE skpd (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(255) NOT NULL,
    nama VARCHAR(255),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    created_by BIGINT,
    updated_by BIGINT
);

CREATE INDEX idx_skpd_uuid ON skpd USING HASH (uuid);

CREATE TABLE kode_pajak (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(255) NOT NULL,
    nama VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    created_by BIGINT,
    updated_by BIGINT
);

CREATE INDEX idx_kode_pajak_uuid ON kode_pajak USING HASH (uuid);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    nama VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL CHECK (role IN ('ADMIN', 'USER')),
    skpd_id BIGINT REFERENCES skpd(id),
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),
    created_by BIGINT,
    updated_by BIGINT
);

CREATE INDEX idx_users_uuid ON users USING HASH (uuid);
